spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

# Data Rest
  data.rest.base-path: /data

server.port: 1234

#logging.level.org.springframework: DEBUG
#debug: true
#trace: true