server:
  port: 1234

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Data Rest
  data.rest.base-path: /data  

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging.level.org.springframework: DEBUG
#debug: true
#trace: true